import redis
rd = redis.Redis('localhost')
key = 'Chelsea_Manchester United_2018'
dict1 = {1:'Antonio Rudiger_PASSED',2:'Andreas Christensen_DRIBBLES',3:'Marcos Alonso_SHOOTS',4:'Davide Zappacosta_DRIBBLES',5:'Eric Bailly_OFFSIDE',6:'Victor Lindelof_CORNER',7:'Luke Shaw_CHANCE',8:'Diogo Dalot_DRIBBLES',9:'Jorginho_TACKLED',10:'Mateo Kovacic_GOAL_Olivier Giroud_ASSIST',11:'Ross Barkley_OUT_Danny Drinkwater_IN',12:'Nemanja Matic_FOUL',13:'Paul Pogba_PASSED',14:'Juan Mata_DRIBBLES',15:'Olivier Giroud_DRIBBLES',16:'Eden Hazard_DRIBBLES',17:'Pedro_OFFSIDE',18:'Marcus Rashford_CORNER',19:'Anthony Martial_CHANCE',20:'Jesse Lingard_YELLOW',21:'Kepa_SAVED',22:'Sergio Romero_SAVED',23:'Eric Bailly_PASSED',24:'Victor Lindelof_DRIBBLES',25:'Luke Shaw_SHOOTS',26:'Diogo Dalot_DRIBBLES',27:'Antonio Rudiger_OFFSIDE',28:'Andreas Christensen_CORNER',29:'Marcos Alonso_CHANCE',30:'Davide Zappacosta_DRIBBLES',31:'Nemanja Matic_TACKLED',32:'Paul Pogba_GOAL_',33:'Juan Mata_PASSED',34:'Jorginho_FOUL',35:'Mateo Kovacic_PASSED',36:'Danny Drinkwater_DRIBBLES',37:'Marcus Rashford_DRIBBLES',38:'Anthony Martial_DRIBBLES',39:'Jesse Lingard_OFFSIDE',40:'Olivier Giroud_CORNER',41:'Eden Hazard_CHANCE',42:'Pedro_YELLOW',43:'Kepa_SAVED',44:'Sergio Romero_SAVED',45:'Antonio Rudiger_PASSED',46:'Andreas Christensen_DRIBBLES',47:'Marcos Alonso_SHOOTS',48:'Davide Zappacosta_DRIBBLES',49:'Eric Bailly_OFFSIDE',50:'Victor Lindelof_CORNER',51:'Luke Shaw_CHANCE',52:'Diogo Dalot_DRIBBLES',53:'Jorginho_TACKLED',54:'Mateo Kovacic_DRIBBLES',55:'Danny Drinkwater_TACKLED',56:'Nemanja Matic_GOAL_',57:'Paul Pogba_PASSED',58:'Juan Mata_DRIBBLES',59:'Olivier Giroud_DRIBBLES',60:'Eden Hazard_DRIBBLES',61:'Pedro_OFFSIDE',62:'Marcus Rashford_CORNER',63:'Anthony Martial_CHANCE',64:'Jesse Lingard_DRIBBLES',65:'Kepa_SAVED',66:'Sergio Romero_SAVED',67:'Eric Bailly_PASSED',68:'Victor Lindelof_DRIBBLES',69:'Luke Shaw_SHOOTS',70:'Diogo Dalot_DRIBBLES',71:'Antonio Rudiger_OFFSIDE',72:'Andreas Christensen_GOAL_',73:'Marcos Alonso_CHANCE',74:'Davide Zappacosta_DRIBBLES',75:'Nemanja Matic_TACKLED',76:'Paul Pogba_PASSED',77:'Juan Mata_PASSED',78:'Jorginho_FOUL',79:'Mateo Kovacic_PASSED',80:'Danny Drinkwater_DRIBBLES',81:'Marcus Rashford_DRIBBLES',82:'Anthony Martial_DRIBBLES',83:'Jesse Lingard_GOAL_',84:'Olivier Giroud_CORNER',85:'Eden Hazard_CHANCE',86:'Pedro_DRIBBLES',87:'Kepa_SAVED',88:'Sergio Romero_SAVED',89:'Andreas Christensen_CHANCE',90:'game end'}
print(type(dict1))
rd.hmset(key,dict1)
print("Inserted")


