import redis
rd = redis.Redis('localhost')
key = 'Manchester United_Chelsea_2017'
dict1 = {1:'Eric Bailly_PASSED',2:'Luke Shaw_DRIBBLES',3:'Diogo Dalot_SHOOTS',4:'Ashley Young_DRIBBLES',5:'Antonio Rudiger_OFFSIDE',6:'Andreas Christensen_CORNER',7:'Marcos Alonso_CHANCE',8:'Davide Zappacosta_DRIBBLES',9:'Paul Pogba_GOAL',10:'Juan Mata_CHANCEAnthony Martial_ASSIST',11:'Andreas Pereira_OUT_Scott McTominay_IN',12:'Jorginho_FOUL',13:'Mateo Kovacic_PASSED',14:'Ross Barkley_DRIBBLES',15:'Marcus Rashford_DRIBBLES',16:'Anthony Martial_DRIBBLES',17:'Jesse Lingard_OFFSIDE',18:'Olivier Giroud_CORNER',19:'Eden Hazard_CHANCE',20:'Pedro_YELLOW',21:'Sergio Romero_PASSED',22:'Kepa_PASSED',23:'Antonio Rudiger_GOAL',24:'Andreas Christensen_DRIBBLES',25:'Marcos Alonso_SHOOTS',26:'Davide Zappacosta_DRIBBLES',27:'Eric Bailly_OFFSIDE',28:'Luke Shaw_CORNER',29:'Diogo Dalot_CHANCE',30:'Ashley Young_DRIBBLES',31:'Jorginho_TACKLED',32:'Mateo Kovacic_GOAL',33:'Ross Barkley_PASSED',34:'Paul Pogba_FOUL',35:'Juan Mata_GOAL',36:'Scott McTominay_DRIBBLES',37:'Olivier Giroud_DRIBBLES',38:'Eden Hazard_DRIBBLES',39:'Pedro_GOAL',40:'Marcus Rashford_CORNER',41:'Anthony Martial_CHANCE',42:'Jesse Lingard_GOAL',43:'Sergio Romero_SAVED',44:'Kepa_SAVED',45:'Eric Bailly_PASSED',46:'Luke Shaw_DRIBBLES',47:'Diogo Dalot_SHOOTS',48:'Ashley Young_DRIBBLES',49:'Antonio Rudiger_OFFSIDE',50:'Andreas Christensen_CORNER',51:'Marcos Alonso_CHANCE',52:'Davide Zappacosta_DRIBBLES',53:'Paul Pogba_TACKLED',54:'Juan Mata_DRIBBLES',55:'Scott McTominay_TACKLED',56:'Jorginho_FOUL',57:'Mateo Kovacic_PASSED',58:'Ross Barkley_DRIBBLES',59:'Marcus Rashford_GOAL',60:'Anthony Martial_DRIBBLES',61:'Jesse Lingard_OFFSIDE',62:'Olivier Giroud_CORNER',63:'Eden Hazard_CHANCE',64:'Pedro_DRIBBLES',65:'Sergio Romero_PASSED',66:'Kepa_PASSED',67:'Antonio Rudiger_PASSED',68:'Andreas Christensen_DRIBBLES',69:'Marcos Alonso_SHOOTS',70:'Davide Zappacosta_DRIBBLES',71:'Eric Bailly_OFFSIDE',72:'Luke Shaw_CORNER',73:'Diogo Dalot_DRIBBLES',74:'Ashley Young_DRIBBLES',75:'Jorginho_TACKLED',76:'Mateo Kovacic_PASSED',77:'Ross Barkley_PASSED',78:'Paul Pogba_DRIBBLES',79:'Juan Mata_PASSED',80:'Scott McTominay_DRIBBLES',81:'Olivier Giroud_DRIBBLES',82:'Eden Hazard_DRIBBLES',83:'Pedro_OFFSIDE',84:'Marcus Rashford_CORNER',85:'Anthony Martial_CHANCE',86:'Jesse Lingard_YELLOW',87:'Sergio Romero_PASSED',88:'Kepa_PASSED',89:'Eric Bailly_CHANCE',90:'game end'}
print(type(dict1))
rd.hmset(key,dict1)
print("Inserted")


